#
# $Id: Makefile,v 1.10 2000-06-01 17:57:44 fjoe Exp $
#

MODULE=		magic
MODULE_ID=	MOD_MAGIC
CFILES=		init_magic.c magic.c _magic.c act_magic.c spellfun.c spellfun2.c

.include "../Makefile.module"
