#
# $Id: Makefile,v 1.5 2003-10-10 16:14:17 fjoe Exp $
#

MODULE=		bootdb
SRCS=		init_bootdb.c db_area.c db_clan.c db_class.c db_cmd.c\
		db_effect.c db_form.c db_glob_gmlstr.c db_handler.c\
		db_hometown.c db_lang.c db_liquid.c db_material.c db_race.c\
		db_skill.c db_social.c db_spec.c db_system.c

.include <bsd.prog.mk>
