#
# $Id: Makefile,v 1.3 2002-03-21 13:30:31 fjoe Exp $
#

MODULE=		bootdb
SRCS=		init_bootdb.c db_area.c db_clan.c db_class.c db_cmd.c\
		db_effect.c db_form.c db_glob_gmlstr.c db_hometown.c\
		db_lang.c db_liquid.c db_material.c db_race.c db_skills.c\
		db_socials.c db_spec.c db_system.c

.include <bsd.prog.mk>
