#
# $Id: Makefile,v 1.6.2.2 2002-08-31 17:18:49 tatyana Exp $
#

MODULE = dofun
CFILES = act_comm.c act_info.c act_move.c act_obj.c act_wiz.c\
	 cast.c dofun.c healer.c hunt.c martial_art.c note.c\
	 quest.c mining.c fishing.c

.include "../Makefile.module"

