#
# $Id: Makefile,v 1.11 2002-11-23 18:02:30 fjoe Exp $
#

MODULE=		dofun
SRCS=		init_dofun.c act_comm.c act_info.c act_move.c act_obj.c\
		act_spec.c act_wiz.c healer.c hunt.c martial_art.c note.c\
		toggle.c

.include <bsd.prog.mk>
