#
# $Id: Makefile,v 1.2 1999-06-24 20:34:55 fjoe Exp $
#

MODULE_NAME = dofun.so

CFILES = act_comm.c act_info.c act_move.c act_obj.c act_wiz.c\
	 dofun.c martial_art.c quest.c

.include "../Makefile.module"

