#
# $Id: Makefile,v 1.3 1999-07-02 12:54:58 fjoe Exp $
#

MODULE_NAME = olc.so.$(ABI_VERSION)

CFILES = olc.c olc_area.c olc_clan.c olc_help.c olc_lang.c olc_mob.c\
	 olc_mpcode.c olc_msg.c olc_obj.c olc_room.c olc_rule.c\
	 olc_social.c

.include "../Makefile.module"

