#
# $Id: Makefile,v 1.12 1999-12-07 14:20:59 fjoe Exp $
#

MODULE = olc
CFILES = olc.c olc_area.c olc_clan.c olc_class.c olc_help.c olc_lang.c\
	 olc_liquid.c olc_material.c olc_mob.c olc_mpcode.c olc_msg.c\
	 olc_obj.c olc_race.c olc_room.c olc_rule.c olc_skill.c olc_social.c

.include "../Makefile.module"

