#
# $Id: Makefile,v 1.19 2001-08-26 05:49:12 fjoe Exp $
#

MODULE=		olc
SRCS=		olc.c olc_area.c olc_clan.c olc_class.c olc_cmd.c olc_damtype.c\
		olc_help.c olc_hint.c olc_lang.c olc_liquid.c olc_material.c\
		olc_mob.c olc_mprog.c olc_msg.c olc_obj.c olc_race.c\
		olc_room.c olc_rule.c olc_skill.c olc_social.c olc_spec.c

.include <bsd.prog.mk>
