#
# $Id: Makefile,v 1.18 2003-10-10 14:28:20 fjoe Exp $
#

MODULE=		sog
SRCS=		init_sog.c act.c affects.c ban.c comm.c fight.c\
		handler.c interp.c magic.c mccp.c mudftp.c name_edit.c\
		rating.c reset.c save.c scan_pfiles.c skills.c spec.c\
		string_edit.c
SRCS+=		charset.c handler_impl.c info.c nanny.c skills_impl.c

.include <bsd.prog.mk>
