#
# $Id: Makefile,v 1.7 2001-08-05 16:36:41 fjoe Exp $
#

MODULE=		handler
SRCS=		init_handler.c act.c affects.c effects.c fight.c handler.c\
		name_edit.c rating.c reset.c save.c scan_pfiles.c skills.c\
		spec.c string_edit.c\
		handler_impl.c skills_impl.c

.include <bsd.prog.mk>
