#
# $Id: Makefile,v 1.6 2001-08-03 12:21:02 fjoe Exp $
#

MODULE=		handler
SRCS=		init_handler.c act.c affects.c effects.c fight.c handler.c\
		name_edit.c rating.c reset.c save.c scan_pfiles.c skills.c\
		spec.c string_edit.c\
		skills_impl.c

.include <bsd.prog.mk>
