#
# $Id: Makefile.module,v 1.5 2000-06-01 17:57:23 fjoe Exp $
#

#
# modules rules
#

.include "../Makefile.osdep"

CFLAGS+=	$(SO_CFLAGS)
LDFLAGS+=	$(SO_LDFLAGS)

.if defined(MODULE_ID)
CFLAGS+=	-DMODULE_IMPL=${MODULE_ID}
.endif

INSTALL_DIR=	modules

