#
# $Id: Makefile.module,v 1.2 1999-06-24 21:07:42 fjoe Exp $
#

#
# modules rules
#

.include "../Makefile.inc"

CFLAGS += $(SO_CFLAGS)
LFLAGS += $(SO_LFLAGS)

INSTALL_DIR = modules

.include "../Makefile.rules"
