#
# $Id: Makefile.rules,v 1.6 1999-07-22 09:10:51 avn Exp $
#

#
# core version
#
ABI_VERSION = 3

#
# common rules
#

OFILES != for i in `echo $(CFILES) | sed 's/\.c/.o/g'`; do basename $${i}; done

all: $(MODULE_NAME)

$(MODULE_NAME): $(OFILES)
	$(LD) -o $(MODULE_NAME) $(LFLAGS) $(OFILES) $(LIBS)

depend:
	mkdep $(CFLAGS) $(CFILES)

clean:
	rm -f $(MODULE_MASK) $(OFILES) .depend

install: $(MODULE_NAME)
	install $(INSTALL_FLAGS) $(MODULE_NAME) $(INSTALL_PATH)/$(INSTALL_DIR)

