#!/bin/sh
#
# this shell script is intended for debugging purposes
# do not use autorun to debug mud server and do not use
# this script in production use
#
umask 002
port="-p 6666 -i 6667"
sog=bin/sog
index=1000
cd ..

# Set limits.
if [ -e shutdown.txt ]; then
	rm -f shutdown.txt
fi

while [ 1 ]; do
	if [ -r tmp/lastlog ]; then
		index=`cat tmp/lastlog`
	fi

	while [ 1 ]; do
		logfile=log/$index.log
		if [ -e $logfile ]; then
			index=`echo $index + 1 | bc`
		else
			break
		fi
	done

	echo $(($index+1)) > tmp/lastlog
	$sog $port 2>&1 | tee $logfile
	exitcode=$?

	if [ -e sog.core ]; then
		mv sog.core corefiles/core.$index
	fi

	if [ -e shutdown.txt ]; then
		rm -f shutdown.txt
		exit 0
	fi

	if [ $exitcode -ne 0 ]; then
		exit 1
	fi
done
