#ifndef _RESOURCE_H_
#define _RESOURCE_H_

/*
 * $Id: resource.h,v 1.8 1998-04-18 04:05:26 efdi Exp $
 */

char* msg(int resnum, int lang);

#define LANG_ENG 0
#define LANG_RUS 1

enum {
	INFO_NOTHING = 1, 

	EQ_USED_AS_LIGHT,
	EQ_WORN_ON_FINGER_1,
	EQ_WORN_ON_FINGER_2,
	EQ_WORN_AROUND_NECK_1,
	EQ_WORN_AROUND_NECK_2,
	EQ_WORN_ON_TORSO,
	EQ_WORN_ON_HEAD,
	EQ_WORN_ON_LEGS,
	EQ_WORN_ON_FEET,
	EQ_WORN_ON_HANDS,
	EQ_WORN_ON_ARMS,
	EQ_WORN_AS_SHIELD,
	EQ_WORN_ABOUT_BODY,
	EQ_WORN_ABOUT_WAIST,
	EQ_WORN_AROUND_WRIST_1,
	EQ_WORN_AROUND_WRIST_2,
	EQ_WIELDED,
	EQ_HELD,
	EQ_FLOATING_NEARBY,
	EQ_SCRATCHED_TATTOO,
	EQ_DUAL_WIELDED,
	EQ_STUCK_IN,

	INFO_SLEEPING_AT,
	INFO_SLEEPING_ON,
	INFO_SLEEPING_IN,
	INFO_SLEEPING,
	INFO_RESTING_AT,
	INFO_RESTING_ON,
	INFO_RESTING_IN,
	INFO_RESTING,
	INFO_SITTING_AT,
	INFO_SITTING_ON,
	INFO_SITTING_IN,
	INFO_SITTING,
	INFO_STANDING_AT,
	INFO_STANDING_ON,
	INFO_STANDING_IN,
	INFO_STANDING,
	INFO_FIGHTING,
	INFO_IS_HERE,

	INFO_IS_IN_PERFECT_HEALTH,
	INFO_HAS_A_FEW_SCRATCHES,
	INFO_HAS_SOME_SMALL_BUT_DISGUSTING_CUTS,
	INFO_IS_COVERED_WITH_BLEEDING_WOUNDS,
	INFO_IS_GUSHING_BLOOD_M,
	INFO_IS_GUSHING_BLOOD_F,
	INFO_IS_WRITHING_IN_AGONY,
	INFO_IS_CONVULSING_ON_THE_GROUND,
	INFO_IS_NEARLY_DEAD,

	INFO_POS_NAME_DEAD_M,
	INFO_POS_NAME_MORTALLY_WOUNDED_M,
	INFO_POS_NAME_INCAPACITATED_M,
	INFO_POS_NAME_STUNNED_M,
	INFO_POS_NAME_SLEEPING_M,
	INFO_POS_NAME_RESTING_M,
	INFO_POS_NAME_SITTING_M,
	INFO_POS_NAME_FIGHTING_M,
	INFO_POS_NAME_STANDING_M,
	INFO_POS_NAME_DEAD_F,
	INFO_POS_NAME_MORTALLY_WOUNDED_F,
	INFO_POS_NAME_INCAPACITATED_F,
	INFO_POS_NAME_STUNNED_F,
	INFO_POS_NAME_SLEEPING_F,
	INFO_POS_NAME_RESTING_F,
	INFO_POS_NAME_SITTING_F,
	INFO_POS_NAME_FIGHTING_F,
	INFO_POS_NAME_STANDING_F,

	INFO_YOU_ARE,
	INFO_YOU_ARE_CARRYING,
	
	COMM_SWITCH_TO_RUSSIAN,
	COMM_SWITCH_TO_ENGLISH,
	COMM_SHOW_LANGUAGE,
	COMM_LANGUAGE_USAGE,

	INFO_COND_EXCELLENT,
	INFO_COND_GOOD,
	INFO_COND_FINE,
	INFO_COND_AVERAGE,
	INFO_COND_POOR,
	INFO_COND_FRAGILE,

	UPDATE_WEATHER_DAY_BEGUN,
	UPDATE_WEATHER_SUN_IN_THE_EAST,
	UPDATE_WEATHER_SUN_IN_THE_WEST,
	UPDATE_WEATHER_NIGHT_BEGUN,
	UPDATE_WEATHER_GETTING_CLOUDY,
	UPDATE_WEATHER_IT_STARTS_TO_RAIN,
	UPDATE_WEATHER_THE_CLOUDS_DISAPPEAR,
	UPDATE_WEATHER_LIGHTNING_FLASHES,
	UPDATE_WEATHER_THE_RAIN_STOPPED,
	UPDATE_WEATHER_LIGHTNING_STOPPED,

	MOVE_LEAVES_M,
	MOVE_LEAVES_F,
	MOVE_LEAVES_RIDING_ON_M,
	MOVE_LEAVES_RIDING_ON_F,
	MOVE_LEAVES_T_M,
	MOVE_LEAVES_T_F,
	MOVE_LEAVES_T_RIDING_ON_M,
	MOVE_LEAVES_T_RIDING_ON_F,
	MOVE_ARRIVED_M,
	MOVE_ARRIVED_F,
	MOVE_ARRIVED_RIDING_M,
	MOVE_ARRIVED_RIDING_F,

};

#endif
