#
# $Id: Makefile,v 1.1 2000-03-28 21:59:37 fjoe Exp $
#

.PATH: ${.CURDIR}/../sog

MODULE_NAME=	hashtest
OFILES=		hashtest.o hash.o varr.o strkey_hash.o str.o

.include "../Makefile.osdep"

CFLAGS+= -DHASHTEST
