#
# $Id: Makefile,v 1.2 2001-06-16 18:49:58 fjoe Exp $
#

PROG=		hashtest
SRCS=		hashtest.c\
		hash.c varr.c strkey_hash.c str.c

.include <bsd.prog.mk>

.PATH:		${.CURDIR}/../sog
CFLAGS+=	-DHASHTEST
